# 部署到bcc的服务提供方

version: '3'

services:
  db:
    image: library/mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: azusa520
    ports:
      - 3306:3306
  redis:
    image: redis
    restart: on-failure
    ports:
      - 6379:6379