server:
  servlet:
    context-path: /api/v1

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://119.45.30.109:3306/little_blog?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss

mybatis-plus:
  type-aliases-package: cn.az.blog.admin.entity
  global-config:
    banner: off
    db-config:
      id-type: assign_uuid
