server:
  servlet:
    context-path: /api/v1
  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://180.76.169.35:3306/little_blog?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: azusa520
      driver-class-name: com.mysql.cj.jdbc.Driver
      validation-query: SELECT 1
      initial-size: 10
      max-active: 50
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filters: stat,wall
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss

  redis:
    host: 180.76.169.35
    port: 6379
    password: azusa520
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

mybatis-plus:
  type-aliases-package: cn.az.blog.admin.entity
  configuration:
    jdbc-type-for-null: null
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: off

jwt:
  secret: azusachino
  expiration: 36000
  access-header: Authorization
  token-header: LittleBlog
